import React, { useState } from "react";
import "../../../App.scss";
import "../Publications.scss";
import { BrowserRouter as Router, Switch, Route } from "react-router-dom";
//Components
import Hero from "../../../components/Hero/Hero";
import Footer from "../../../components/Footer/Footer";
import Article from "../../../components/Article/Article";
import OnlineArticle from "../../OnlineArticle/OnlineArticle";

//Resources
const heroImg = require("../../../images/heroPublications.jpg");
const art1Img = require("../../../images/articles/online/art1Img.png");
const PublicationsEng = ({ isEng }) => {
  const [onlineArticle, setOnlineArticle] = useState({
    paragraphs: ["Test paragraph 1", "Test paragraph 2", "Test Paragraph 2"],
    title: "Article title",
    img: { art1Img },
    description:
      "This is an article about a very important topic where I am discussing a thi",
  });
  return (
    <Router>
      <Switch>
        <Route path="/publications/onlineArticle">
          <OnlineArticle onlineArticle={onlineArticle} isEng={isEng} />
        </Route>
        <Route exact path="/publications">
          <div className="Publications">
            <Hero
              img={heroImg}
              imgDescription="Writing in a notebook"
              text="Publications"
            />
            <div id="content">
              <div id="online" className="fullWidth">
                <h2 className="listHeader">Online</h2>
                <Article
                  thumbnail={require("../../../images/articles/online/art1Img.png")}
                  title="Cross-cultural management and communication"
                  description="although recognized as one of the key competencies of the 21st century manager, is often underestimated.
                  This article is about one of the most important, and at the same time one of the most ignored, competencies of the 21st century manager in Poland and other places in the world."
                  paragraphs={[
                    "HEADER Cross-cultural management and communication - key competency for global manager",
                    "Cross-cultural management and communication, although recognized as one of the key competencies of the 21st century manager, is often underestimated. This article is about one of the most important, and at the same time one of the most ignored, competencies of the 21st century manager in Poland and other places in the world.",
                    "This article is about one of the most important, and at the same time one of the most ignored, competencies of the 21st century manager in Poland and other places in the world.",
                    "HEADER The key competency of 21st century",
                    "Years ago, when the Polish transformation began, expats were seen as somebody unique; they were treated respectfully and were often blindly believed in their business and life wisdoms. Cross-cultural adaptation, as it exists today, was not an issue, as Polish workers simply needed to accept the perceived strange habits of their expat bosses. Cross-cultural adaptation was certainly not a central issue for HR departments. ",
                    "Today the situation has changed dramatically. Expats are no longer perceived as people of special status. Shared Service Centers have became an integral part of the business landscape and work in international virtual project teams has become an everyday reality. More and more Poles move up the career ladder to sit on Boards of Directors of international companies together with their foreign colleagues. This ability to work effectively in cross-cultural teams has become the key competency of modern-day HR. Sending local employees – no matter how talented – to foreign countries without the appropriate cultural awareness preparation can often result in his or her failure, dismissal from the company, and, all in all, enormous costs.",
                    "HR employees who are responsible for sending and receiving expats mainly focus on the physical side of the relocation process: finding accommodation and school for kids, explaining how to use local medical facilities and where to shop. Of course all this information is necessary and critically important – but it is not sufficient. We often forget about the soft side of relocation. For example, the majority of employees from Asia will find it uncomfortable to speak up during meetings dominated by European “alpha men”. This is because in many Asian cultures the open voicing of opinions, especially in the presence of high-level bosses, is extremely awkward and embarrassing. One the one hand, forcing a culturally unaware employee to partake in such discussion will end in feelings of frustration, rejection and an impression that the group is arrogant and aggressive. On the other hand, Western co-workers might start questioning what is the added value to the discussion brought by a teammate who does not speak.",
                    "Here we are faced with a classical cross-cultural communication barrier and different cultural DNA. However by simply adjusting the meeting facilitation style it is possible to open the discussion space for everyone.",
                    "HEADER My personal experience",
                    "When I think about the beginning of my adventure with studying other cultures, I always remember my first trip abroad. In the mid-80s, after my second year of Arabic at university in Poland, I received a scholarship to Al-Mustansiriya University in Bagdad and journeyed to study the language. Those were entirely different times, as Poles could not hold their own passports at home, a special permission called a “green card” was needed to cross the border, and the average salary in Poland approximated only 20-30 USD per month (of course by black market standards, as one could not even buy dollars by an official rate).",
                    "The first day after my arrival in Bagdad, I was walking along the street and ahead of me are two soldiers with Kalashikov’s machine guns. They were walking and… holding each other’s hand. At the time that I was shocked; in my culture men do not hold each other’s hand when walking. Very quickly it was explained to me that in Arabic culture this behavior is absolutely normal for good friends, and there is no sexual connotation at all. This was my first “aha” moment – the revelation and true eye-opener that all the things I considered “normal” and “universal”, were not necessarily the same for others.",
                    "Many years have passed from that “aha” moment. I had the privilege to work for an international corporation for an extensive time. Together with my family we moved from Poland to Ukraine, Dubai, China, Russia, Indonesia and Hong Kong. I have had bosses of 14 different nationalities and I have worked with truly international teams. I have tested the good and bad HR practices on my and my family’s own skins and I have made many mistakes, some of them quite funny, others rather serious. The 18 years of work outside my country, on different continents and in diverse roles, has taught me a lot. For example, that the “cultural glasses” we have obtained by virtue of growing up in a certain society determine how we see the world around us. That there is no single reality, but rather a multitude of realities created by each individual perceiver. Each of us wears these cultural glasses, but not all of us are aware they are there. During my years abroad I learnt humility and a great respect for others. Cross-cultural communication and management have become my passion and I want to share this knowledge with you.",
                    "HEADER The key role of HR",
                    "The modern-day HR manager must be a cross-cultural interpreter between foreign employees and the local team. Conflicts, which will undoubtedly appear sooner or later when working in international environments, have many root causes. They might be related to: a different perception of time, directness or indirectness in communication styles, whether one considers the boss as an approachable close workmate or rather a distant hierarch whose opinion should not be questioned. We also need to remember that a poorly chosen style of providing employee feedback might cause the employee to react differently than desired. All the above-mentioned aspects are much more important for achieving commercial success than we might have originally thought.",
                    "It is precisely for this reason that the “Cross-cultural roller-coaster” series about communication and management in international environments was created. I will tell you about theory and share my HR experiences as I have both managed inter-cultural teams and was part of those teams myself. I invite you to share your own cross-cultural experiences and challenges in this area as well.",
                  ]}
                  isLeft={true}
                  isPrint={false}
                  setOnlineArticle={setOnlineArticle}
                />
                <Article
                  thumbnail={require("../../../images/articles/online/art3Img.png")}
                  title="Face as key personal asset"
                  description="The concept of “having face” is a valuable asset, which is builds through relations with others and fulfilling ones role in society, in the firm, family, or circle of acquaintances. The phenomenon of “losing face” exists throughout the whole world, as in the end no one likes to be looked down upon, embarrassed, and humiliated. However the importance of “having face” is much more significant in the East than in the West."
                  paragraphs={[
                    "HEADER The concept of “having face” is a valuable asset,",
                    "which is builds through relations with others and fulfilling ones role in society, in the firm, family, or circle of acquaintances. The phenomenon of “losing face” exists throughout the whole world, as in the end no one likes to be looked down upon, embarrassed, and humiliated. However the importance of “having face” is much more significant in the East than in the West.",
                    "“Loosing face” is one of the most important factors affecting people’s behavior in many countries in the Middle East and Asia, especially in China, Japan, Korea and Indonesia. In Mandarin Chinese this concept is called “mei-mianzi” – literally to not have a face. In the recent years more and more Asian corporations are appearing in Poland; one just needs to mention mobile phone giants, personal electronics or online shopping. Along with these companies expat managers of both middle- and higher-ranks are moving to Poland. The stress of inter-cultural tension is as high for them as it is for us Poles. More and more often HR will be faced with conflicts between “dictatorial” Asian bosses (from the Poles perspective), and the “arrogant, lacking culture and etiquette” European workers (from the Asian manager’s perspective).",
                    "HEADER The East and West in Practice",
                    "In the business culture of Western firms it is expected that an employee will, in a cordial manner, demonstrate his or her point of view. When looking within the corporation for people with high potential, the so-called “talents”, the ability to express one’s ideas and to control confrontation with the group or boss are absolute necessities. Simply transferring this rule to Asian firms will end in misunderstandings. This was one of my experiences from Indonesia – the company where I worked, as well as other Western corporations, sent their talented, high potential employees to Europe for short-and medium-length internships. We were sending experienced people, who had managed large teams and were exemplary in their work in their own country. They embarked on the overseas internships to experience a different perspective, make new contacts, and also to be presented to and assessed by the “top of the top”. Unfortunately at the beginning this program did not work as planned. Most employees returned with a rather cold than enthusiastic evaluation. Their ability to express own opinion and to bring something new to the discussion were questioned, as they were not speaking up during discussion and meetings with high-rank managers.",
                    "After closer inspection of the problem, we understood – that it was us, as the senders, who had made the mistake of “assuming”. We assumed that people who were doing a great job in Indonesia would demonstrate those same behaviors sitting at a conference in our global corporate HQ. However by virtue of the concept of “face” and respect for hierarchy, our employees were unable to demonstrate their strong sides in a new environment. One returning manager told me: “How can I speak without being asked, when the Regional President is sitting in on the conference? Moreover my European colleagues are loudly debating amongst each other and are not letting me speak. If I interrupt them I will appear as lacking manners and respect for others.”",
                    "They were right, most of us can not simple change culture driven behaviors. As a result we invested in serious cross-cultural preparation before sending our employees for the next overseas internships. We explained the difference in expected behavior, practiced short scenes to place them outside of their comfort zone, and assigned coaches and mentors. The next batch of employees leaving abroad understood to a greater extent the rules of the game and did a significantly better job. Ironically, they faced the same problem upon returning to Indonesia. After a yearlong placement they were able to adapt well their behavior to HQ’s expectations that, upon coming back, they themselves started to be perceived as little arrogant and not following the local rules. In order to function well between cultures, they had to learn to dynamically adapt their behavior to the culture they were operating at the moment. As they later agreed, going outside of their cultural comfort zone was one the greatest benefits of their placement in Europe.",
                    "HEADER Other ways of “losing face”",
                    "Openly saying “no”, especially to one’s boss, will instantly result in “lose of face”. This will be the case both for the employee who dared to publically and openly express his or her opinion, as well as for the boss who, by virtue, was ridiculed by his or her employee. The fear of losing face can be so strong that the typical Asian employee will not openly speak the whole truth, so that both sides can keep “face”. In the previous article I already mentioned the problems of openly saying “no”. Working with my Chinese team, I was confused when, despite my encouragement, I didn’t hear them say: “You’re wrong, we think this ought to be done differently”. If they were to say that, both they and I would lose face. To prevent this from happening, they stayed silent. Often such information is expressed, but it is us who cannot understand it. What is important is not only what is said, but also what is not said. The latter can communicate rejection, which we, with our cultural glasses, simply do not perceive. I was involved in business negotiations in China, which I originally perceived as successful and likely to lead to the signing of a contract. However later my Chinese colleagues explained to me that the other side completely does not agree with our proposals.",
                    "When they said, “Hmm, this could be an interesting proposal,” in this context meant, “No way, forget about it”. Moreover they completely ignored the second and third paragraphs of our business proposal, which further showed their disagreement and lack of enthusiasm. For them, it was obvious that they told us “no”. They couldn’t have done so in any more direct way, as that would result in both them and us losing face. It is possible to “lose face” in various ways, one of the easiest being publically expressing negative feedback. This is an area where conflicts spark easily, especially for people from countries, where communicating bad news in a direct and straightforward way is the norm.",
                    "Serious problems in this area are faced by multicultural teams whose manager comes from such a direct culture, for example France, where, without realization, he or she destroys the team morale by openly pointing out their mistakes during meetings. Publically pointing out the mistakes of an employee in Asia is one of the most embarrassing punishments, resulting in “loss of face”. Western expats are often oblivious to this fact. Using European tools for team management and giving feedback they are surprise when their “normal” style of communication brings devastating effects.",
                    "Another problem with which managers from Europe often come into contact with is the inability to successfully lead periodical assessment talks, especially if they want to give negative feedback. A typical Asian employee might take every negative feedback very personally and in it sees a reason for “loss of face”. A way I used to deal with this issue was the “de-personification” of the employee, so that the negative information did not personally concern him or her so much. How did this look in practice? When meeting for our periodical assessment, I would place two random objects on my desk, and I asked the employee to imagine that one of these objects is me (Irek) and the other is him, for example Anton. I asked him to tell me about Anton (and this way to take on a third person perspective) – what sort of personal brand Anton is, what are his strengths and how others perceive him. I then asked for suggestions for what should be done to further develop and strengthen Anton. This method allowed me to circumvent the personal nature of the attack and fear of losing face. I was able to successfully communicate relevant information for areas of improvement, and at the same time continue building interpersonal relations and trust.",
                    "HEADER Multi-cultural teams in Poland and the role of HR",
                    "Up until expats from the Far East were a rarity in Poland, this problem only applied to a small group of Poles moving for work to Asia or the Middle East. It was there that they learned through personal experience, sometimes the easy way and sometimes the hard way, of cultural differences. Today however this problem is clearly visible in Poland. According to recent reports, there are over 600 shared business centers in Poland, many of them with a global reach. To get the full picture add “regular” divisions of multinational corporations.",
                    "One of the strategic roles of HR is reducing unproductivity, often associated with misunderstandings resulting from cultural communication differences. Hence it is time to take a series attitude towards multicultural preparation – both for those coming to work in Poland, as well as for our Polish teams in which expats",
                    "I was recently talking with some colleagues from large company managing expat relocation. Truthfully speaking, the picture of HR teams responsible for employee relocation I’m getting is rather bleak. They focus of organizing employment permits, finding accommodation, school for children, and the physical movement of belongings, which is of course important; however not enough. Providing an employee and his family with cultural relocation training and coaching is the absolute minimum that we as HR should provide.",
                  ]}
                  isLeft={true}
                  isPrint={false}
                  setOnlineArticle={setOnlineArticle}
                />
                <Article
                  thumbnail={require("../../../images/articles/online/art4Img.png")}
                  title="Time isn’t the same everywhere."
                  description=" At first glance, it could appear that time flows the same for everyone. And yet a Swiss or German week has a different meaning than an Italian, Spanish or Arabic week."
                  paragraphs={[
                    "HEADER Time differs between places",
                    "In my previous articles I discussed themes associated with awareness of ones own culture, one’s distance towards a superior, and the meaning of “having face”. Today we’ll consider the attitude towards time in different cultures, and the associated traps encountered when working in international teams.",
                    "HEADER Time isn't the same everywhere",
                    "At first glance, it could appear that time flows the same for everyone. And yet a Swiss or German week has a different meaning than an Italian, Spanish or Arabic week. The phrase “it will be ready for tomorrow” spoken by someone from the Netherlands means something completely different than the famous Arabic bukra, meaning tomorrow, which can mean anything from tomorrow to several days, a week, or even sometime in the distant future. There is no need to leave Europe to experience these various attitudes towards and management of time. Compare our Western neighbors: Germany, the Netherlands or Switzerland, with those bordering the Mediterranean Sea: Greece, Italy or Spain. In one area time is precisely structured and planned; in the other it is elastic and creatively chaotic.",
                    "Multicultural researchers divide cultures into monochromic and polychromed categories. In the former time runs linearly, set dates are followed, being on time is important, and only one thing is done at the same time. In the later time is elastic, our priorities change depending on the situation at hand, several actions are carried out at the same time, and so-called “interruptions” are perfectly acceptable.",
                    "HEADER Adjust your presentation to a given culture’s concept of time",
                    "The concepts of time in different cultures will also affect such common undertakings as presentation structure. Your typical presentation, lets say a sales pitch from corporate America, is composed of a fairly short section describing the past, a slightly longer analysis of the present and the longest part describing the future: benefits, advantages, profits... a beautifully painted picture of what is to come once the goal is reached. It concentrates on the future and the concrete financial gains that await us there.",
                    "However if one were to use the same structure whilst presenting a product to a business partner in the Middle East, in all likelihood it will end in failure. For many Eastern cultures, the past is more important than the future. What one has achieved in the past validates and attests to what one can do in the future. A successful presentation will focus on building the presenter’s credibility by talking about the past and the present. And the future? Well, one can plan, but who are we to know what it will look like? This is why one’s presentation should not overly focus on the future, which is in essence the outcome of our abilities past and present.",
                    "You can begin to imagine just how much impact various concepts of time have on the workings of international teams. Workers from the linear time group will regard those from the elastic time group as disorganized, chaotic and unable to meet deadlines. And from the other side, those from the linear time group will be regarded as lacking both elasticity and the ability to make good use of spontaneous business opportunities.",
                    "HEADER Time is money. But is this true for everyone?",
                    "For corporate America, time is money. Profits are easily calculated and carefully planned in calendars. A 9:30 meeting will begin at 9:30 and last precisely as long as planned in the agenda. At the same time, on the other side of the globe, for example in Indonesia, time is more of a material weaved by the participants. A meeting planned for 9:30 might indeed start at that time, but it might also start several minutes later because one or more participants were hindered by something of greater importance...perhaps their supervisor called, maybe a previous meeting overran, or perhaps their priorities simply changed. And of course everyone, other than the anxious and agitated foreigners, fully accepts this.",
                    "Regarding a personal experience of the different concepts of time: years ago, during one of my assignment in Dubai I had to pass through the cross-cultural school at an accelerated pace. My team comprised of a Swiss manager who oversaw Indian and Turkish programmers, several managers from Lebanon and a secretary from India. Moreover we were working on a project for Arabic distributors. This was a very colorful and at the same time professional team, which nonetheless could bring on several headaches.",
                    "Our Swiss manager assumed that our project outline and deadlines, set out during one meeting, were well...simply agreed upon. Yet the next meeting with our distributor started with another discussion of the functioning of individual program modules, as our clients discovered that certain processes work differently or that the program functioning should be changed. For them, what the project encompassed and its timing were still negotiable. For my Swiss friend, something that was agreed upon and planned out should not be changed.",
                    "HEADER Time in Poland",
                    "On the one side, Polish corporate culture appears to be nearer to the linear side on the concept of time spectrum (who of us did not go through time management training?). One the other side, Poles also have an elastic concept of time: the academic quarter, accepting that a meeting might start later than planned, that during a meeting someone’s phone might ring or someone else might ‘pop by’ and disturb our current time set for work. Hence, from a time management perspective, it is relatively easier for Poles to adapt to Middle East and Asian work styles, than it is for Americans or those from the so-called German styled cultures.",
                    "HEADER Role of HR",
                    "Just like with other cultural differences various people’s attitudes towards time cannot be assessed as good or bad, they are just contrasting . We do need, however, to be aware of these differences in order to help multicultural teams work out common standards.",
                    "How to do this? Begin by raising the team’s awareness about various cultural concepts, especially those related to concepts of time. Then during a group seminar suggest they create a team contract, which they as a group will strive to follow. Finally provide support, especially for those members for whom the contract guidelines come into conflict with their natural cultural style.",
                  ]}
                  isLeft={true}
                  isPrint={false}
                  setOnlineArticle={setOnlineArticle}
                />
                <Article
                  thumbnail={require("../../../images/articles/online/art5Img.png")}
                  title="Managing Conflicts"
                  description="Certain people love conflicts; they feel at home embracing them. Others, on the contrary, prefer harmony to discord. Even though we might prefer to sit in a circle, hold hands and sing “kum ba yah”, sooner or later we will be faced with conflict."
                  paragraphs={[
                    "HEADER Certain people love conflicts; they feel at home embracing them. Others, on the contrary, prefer harmony to discord.",
                    "Even though we might prefer to sit in a circle, hold hands and sing “kum ba yah”, sooner or later we will be faced with conflict.",
                    "However, at times it is necessary to firmly put one’s foot down for a budget, project, an additional headcount to a team, or face a boss’ or colleagues’ different opinion. Whether we like it or not, conflicts are an inherent part of corporate lives. In the context of managing multicultural teams, we truly are on a “cross-cultural rollercoaster”, as various cultures approach conflicts in completely different ways. Managing conflicts can be a minefield – one wrong step and we might end up facing painful wounds that will take a long time to heal.",
                    "HEADER Explosive traps",
                    "Western managers working in Asia or the Middle East often stumble into “conflict management” problems. Similar traps await managers working in Poland on international projects – be it in a physical location or the virtual world. Carelessly managed conflicts can “blow up” projects with very high potential, which lowers their chance of success.",
                    "A project team composed of people from cultures, which openly and directly relay negative feedback, as well as people from cultures which value harmony, can quickly run into the problem of mutual perception. Even though the “intellectual potential” of people from both cultural groups is similar, one party will be seen as arrogant, whilst the other will be deemed unable to clearly explain their opinion. This can lead to a lack of motivation and willingness to work together, and overall can negatively impact results.",
                    "As always, the first step to fix this problem is understanding: both of one’s own and other’s cultural glasses, and both of one’s supervisors and employees. The other crucial step to resolving conflict is a humble acceptance that one size does not fit all and choosing the proper communication style to match the situation is necessary.",
                    "HEADER Harmony or discord",
                    "Some cultures value harmony. In many corporations in Asia, conflict is regarded as something that needs to be avoided – hence the reluctance to give employees direct negative feedback and to publically convey that something is not working. Here the attitude to conflict is one of waiting till the problem resolves itself or is no longer important. If there comes a time when a decision needs to be made, feedback given, this should be done indirectly and implicitly. Often a third party – be it someone on the team or an external consultant – is used to convey negative feedback, as he or she acts as a mediator that prevents the two sides from engaging in direct conflict.",
                    "On the contrary, in Western corporations, conflict is often seen as the so-called “manager’s breakfast”, a process in which participants more or less aggressively present their point of view and fight for what is theirs. Here employees do not necessarily consider the wounds inflicted on others. In fact, the ability to enter into direct conflict with others is a required skill for future corporation leaders. The very process of climbing a Western corporation career ladder exemplifies this, as future leaders are chosen through internal company talent acquisition programs, which are based on competition among participants and delivering results. Harmony? Who has the time?",
                    "HEADER Culture shock",
                    "An Asian manager moved to Poland will often be perplexed by the Polish open way of expressing one’s own view, as well as the public and direct nature of disagreement with a supervisor and questioning his or her authority. The Asian manager might perceive this behavior as arrogant, befitting ill-educated people who ruin harmony and do not show respect.",
                    "On the other side, a Western manager who used to “taking problems head on” and openly giving feedback, will experience a shock when moved to Asia. His Asian team will not openly discuss difficulties in the Western style, problems will often be swept under the rug, and employees will prefer to keep silent than disturb the team harmony.",
                    "I witnessed how difficult it was for my Asian colleagues to openly and publically express their opinions with the Regional President present. At the very same time, their Western colleagues were using the occasion to show off their creativity and openness. At the meeting’s conclusion it was the talkative Westerners who were deemed noteworthy for future corporation careers. Their Asian colleagues, although lacking nothing in intellect or experience, could not forget the cultural wisdom they were brought up in: “Who doesn’t know speaks; who knows stays silent”. Sadly, in the end they were rated a lot lower in terms of potential.",
                    "Similarly I remember my shock when, during one of my first presentations in a Russian organization, I was given a lot of negative feedback, especially regarding the main points of my argument: “I disagree”, “I think it should be done differently”, “Why should we do it this way?”. From my perspective, the presentation was a failure, however later on I found out the audience liked it and the project makes sense. When I asked about their earlier negative remarks I was met with bafflement: “Well, we just need to show that we’re thinking”. Later on I discovered that Russians have a much higher index rating of direct and open communication of negative feedback. Communication that I found aggressive and akin to a personal attack was, from their point of view, a healthy discussion.",
                    "In being able to remain diplomatic and understand other cultures, one can effectively minimize these problems. Here are two more examples from my experience of multi-cultural conflicts. Perhaps they will give you some ideas for conflict management in your teams.",
                    "HEADER Japan and Indonesia",
                    "In Japan, group harmony is very important, so openly saying “no” is often difficult. In our HR team we felt conflict and an unspoken tension associated with changes in the organization structure. We knew that during training sessions no one was willing to openly speak about disagreements and problems. So we divided the trainees into groups. We started by asked them to discuss uncertainties amongst themselves, and then a representative from each group would express the groups’ opinion. This method worked well, because the group representative no longer expressed his or her own concerns, and thereby did not “lose face”, but expressed the concerns of the group. We were able to gather lots of valuable information.",
                    "At the beginning of my placement in Indonesia, I committed a cultural blunder, unconsciously undermining a very warm and well-respected local area sales director. I was unable to meet him and apologize for what had happened, because he began to actively avoiding me, in order to sidestep from the conflict. To solve this problem I used a mediator, which I mentioned in the section above. I explained the whole misunderstanding to one of his trusted managers and asked him to pass on my explanations and apologies to the sales director. The method worked, as not only was my explanation accepted, I was appreciated for my willingness to adapt to the local communication method, thus allowing me to regain face.",
                    "Language is often a source of conflict. English has become the universal language of corporations, and e-mails the standard communication channel. However English is not the first language for most of the team, hence, although properly used, people from different cultures might take certain phrases to mean things they do not. (Especially when people from “direct” cultures communicate with people from “high-context” cultures.) For example, if you once write “Hi Irek”, and a second time write “Dear Irek”, someone from a high-context culture might attempt to read in-between the lines to see if you are trying to get a message across.",
                    "Similarly, the way one writes – whether giving a short reply using several words or providing an eloquent Shakespearean style response – can carry much meaning depending on culture. For example many Indonesians found e-mails sent by their Australian colleagues to be cold and aggressive; whilst Australians were simply using a precise and direct communication style which they were brought up with and one that came naturally to them. However consciously implementing several nice words in e-mail correspondence could go a long way to change the Indonesian reception.",
                    "It is often unconsciously, through one’s natural communication style, that one can fall into a communication trap, create unwanted conflicts, destroy one’s reputation or group effectiveness. How can HR help? First of all, do not wait for problems to arise, but foreshadow them and manage them in advance. The need to develop cross-cultural competencies is still an undervalued asset in international corporations; it should be an inherent part of the building blocks of organization culture. There are many available tools on the market: books, training sessions, mentoring and coaching processes both for groups and managers.",
                    "HEADER Areas that HR should work on:",
                    "LISTSTART",
                    "Understanding the situation and cultural dynamics of the group.",
                    "Understanding the accepted form of communication and cultural taboos.",
                    "Helping the organization understand that “being different” does not arise from conscious aggressiveness or the inability to explain oneself.",
                    "Make developing cross-cultural competencies a long-term strategy for building and developing the organization.",
                    "LISTEND",
                  ]}
                  isLeft={true}
                  isPrint={false}
                  setOnlineArticle={setOnlineArticle}
                />
                <Article
                  thumbnail={require("../../../images/articles/online/art7Img.jpg")}
                  title="Poland vs. Malaysia traps"
                  description="Imagine you’re an HR manager in a global company, in which a Polish department cooperates on a day-to-day basis with a team from Malaysia. And suddenly you receive complaints from both sides. The Malaysian team complains about aggression, impoliteness and low flexibility of the Polish colleagues. They, in turn, criticize the Malaysians for lack of feedback and understanding, missed deadlines, and frequent breaks at work."
                  paragraphs={[
                    "HEADER Imagine you’re an HR manager in a global company, in which a Polish department cooperates on a day-to-day basis with a team from Malaysia.",
                    "And suddenly you receive complaints from both sides. The Malaysian team complains about aggression, impoliteness and low flexibility of the Polish colleagues. They, in turn, criticize the Malaysians for lack of feedback and understanding, missed deadlines, and frequent breaks at work (such as when the majority of the Malaysian team suddenly disappears for a long time).",
                    "How HR and line leaders can help both teams?",
                    "HEADER Distant and fascinating Malaysia",
                    "Recently, I conducted a several day-long training in Malaysia. I am very sentimental about this country, as its capital city Kuala Lumpur was the first Asian city I visited years ago, when on a business trip with my previous company.",
                    "The amazing combination of modernity and tradition instantly struck me. I was amazed by Petronas Tower, which was then the tallest building in the world, the convenient network of elevated city trains sprawling across the city, the amazing atmosphere of China Town and Little India, as well as historic landmarks and various tourist attractions. On top of it all were the people: nice, smiling and friendly. Reality later corrected this first ideal image.",
                    "During my later visits I started to see the other side of the coin as well. I was bothered by traffic jams, air humidity, temperature and bureaucracy, the nice and smiling faces seemed increasingly difficult to decipher and I fell into communication traps ever more often.",
                    "There are many similarities between Malaysia and Poland – similar population size (31 million in Malaysia vs. 36 in Poland), similar currency exchange rate with the dollar (around 4 ringgits) or cost of living index. On the other hand, unlike Poland, Malaysia is ethnically and religiously much more diverse. The Malays make up 68% of population, Chinese 23%, Indians 7% and other minorities 2%. The official religion is Islam (over 60% of population), but Buddhism, Hinduism, Taoism, Confucianism and Christianity enjoy freedom and their major holidays are free from work for everyone.",
                    "In my corporate career, I had a fantastic Malaysian boss, who was one of the smartest people I had the privilege to work with. Later, I often supported the local team in various projects. I have great memories of Malaysia and I gladly go back there. This is why, I was really happy when Zofia Baranska from Blackbird proposed we do a joint project for a multi-national company, whose Polish and Malaysian teams came across communication problems.",
                    "HEADER Clash of cultures",
                    "In this project, the HR department in the large global company starts receiving complaints from Malaysian and Polish teams. The Malaysians complain about arrogant attitude and impoliteness of the Polish side, while the Polish team is increasingly frustrated with imprecise communication, low willingness to say “no” or “I do not know”. Additionally, the Malaysians often perform the agreed tasks in a different way without prior consultation. There’s also a problem in long unplanned breaks when all or majority of the team is unavailable. Frustration and accusations are spiralling.",
                    "What’s happening? Assuming that both sides have good intentions and want to achieve their goals, what are the cross-cultural traps they fell into and what is the recipe for future successful Polish-Malaysian cooperation? One glance at Erin Meyer’s map of cross-cultural dimensions reveals that these cultures are located on the opposites sides of the spectrum of cultural dimensions. This could be a highly volatile mixture, especially when these differences and their consequences stay in blind spots of both teams.",
                    "HEADER Stealthy traps of cross-cultural communication",
                    "Let’s have a closer look at the key areas causing these problems and what immediate advice could be given to the team members to remove the current noise affecting their relationship. There are four distinctive points which need to be addressed.",
                    "HEADER A. Keep reading between the lines",
                    "Malaysian culture is much more contextual than Polish culture. This means that Malaysians do not say things directly, and the conversation partner needs to understand the situation and its context in order to correctly read the message. The Polish way of communicating, which is more literal and concrete, will be perceived as impolite, while the Polish open style of conveying negative feedback will be simply seen as aggressive and similar to an attack, triggering defensive mechanisms on the other side.",
                    "HEADER Advice for the Polish team:",
                    "LISTSTART",
                    "both parties communicate in English, however you need to be less direct than “Polish norm”, so give a softer tone to your message by using downgraders, phrases like “a little bit”, “partially”, “maybe”, “could you”",
                    "in emails, add phrases such as “I hope you are doing well”, “thank you in advance for your help and support”, “I wish you a nice day”, which will not only soften the message but will also help build the relation",
                    "in conversations, use simple expressions, avoid idioms, speak slowly, accept the fact that the Malaysian accent will often be a cause of problems and ask with clarifying questions to make sure",
                    "never burst in anger, do not show negative emotions",
                    "LISTEND",
                    "HEADER B. Not saying “no”",
                    "Malaysians express lack of consent in a subtle way. If you hear them say “It’s an interesting idea but it needs some more consideration” or “execution will be hard and will definitely take more time”, then you need to view these sentences as a clear “no” or lack of understanding. Saying “no” directly or admitting openly to lack of understanding causes one to lose face, which is very significant in Eastern cultures, much more so than in Poland.",
                    "HEADER Advice for the Polish team:",
                    "LISTSTART",
                    "read between the lines as you’ll never hear a direct disagreement or negation",
                    "look out for signals that something is very hard to do, which most often means lack of consent",
                    "don’t use the tactic of cornering someone, it will not be effective, if you push for a clear “is it a yes or no”, you’ll most often hear “yes” but you’ll be surprised and disappointed later",
                    "remember that harmony is highly important, your direct “No” will be seen as aggressive, which may cause a communication paralysis",
                    "LISTEND",
                    "HEADER C. Keep relations in the centre of attention",
                    "Malaysian culture is very focused on relations and personal bonds, which is why the sense of belonging to a group, company, family or community is very important. The Malaysian attitude can be summed up as, “I work with you because I know you, because we go to lunch together, because we share private stories.” If you go to lunch alone, you can expect signs of care and questions such as “what happened, what problem do you have, how can we help?” Lunch is simply a group event. However these group outings were seen as the cause of discontent of the Polish team, who openly escalated the problem with their superiors in writing. This, however, only worsened the situation, because Malaysian culture is much more hierarchical than in Poland, so a complaint sent to the superior caused storms and loss of face.",
                    "HEADER Advice for the Polish team:",
                    "LISTSTART",
                    "sitting in offices a few thousand miles away and 6 time zones apart, building relations isn’t easy but it’s perfectly possible",
                    "during conversations, spend some time asking about private matters and sharing some of your own related to e.g. family, hobby, holidays, weather… Don’t be surprised if the other person touches very private issues, e.g. religion, which is a perfectly acceptable question in cultures focused on relations",
                    "personalize the correspondence, adding personal notes will be well received",
                    "LISTEND",
                    "HEADER D. Remember the boss is always right",
                    "Hierarchy in Malaysia is much more important than in Poland. One does not discuss or dispute with the boss; one executes his orders. Openly expressing one’s opinion means loss of face, group ostracism and often a layoff. As much as multinational corporations implement a culture with more openness and stimulation for expressing own opinions, in local companies and administrations this behaviour is simply unthinkable. In addition, there’s also the pride in one's own country and its achievements to be considered. Malaysia is one of the Asian tigers, with well-developed IT and electronic sectors and its urban infrastructure is better than in many European countries. It also has stunning nature and is a paradise for tourists. The slogan “Malaysia Truly Asia” is a recognizable brand in the world.",
                    "HEADER Advice for the Polish team:",
                    "LISTSTART",
                    "there’s a proverb in the East that a captain speaks to a captain and a general speaks to a general, meaning you should stay at your level of communication, never ask anything of your partner’s subordinate without asking for partner’s consent first",
                    "bypassing hierarchy in communication will result in chaos and will be seen as lack of respect",
                    "think twice before adding superiors in CC (unless it’s a praise), including superiors in correspondence causes much more stress than in Poland",
                    "never ask for an opinion of a subordinate of your conversation partner, you will create an awkward situation for everyone and you won’t hear anything different than full agreement with the superior",
                    "LISTEND",
                    "HEADER Recipe for leaders and HR",
                    "Cultural customs are deeply embedded, often on the level of values. Cross-cultural intelligence isn’t about fully adapting to the other side or, the opposite, about changing partners’ behavior at any price. Cross-cultural intelligence is about awareness of differences and their consequences for business; it’s about wise building of synergies and addressing potential conflicts. As a leader or HR Business Partner, you should take care of:",
                    "LISTSTART",
                    "team’s awareness of the existence of cultural differences",
                    "diagnosing crucial communication problems",
                    "designing short-term and long-term solutions",
                    "implementing them",
                    "building organizational culture",
                    "LISTEND",
                    "HEADER From Malaysian perspective",
                    "During a workshop, which I recently conducted in Kuala Lumpur, I went with my Malaysian colleague for dinner and asked him what he thinks of cooperation with Europeans. He admitted, it could be very frustrating. Our direct communication style is seen by Malaysian as aggressive and our routine of adding superiors in cc. in correspondence is like letting a bull into a porcelain shop. Lastly, he said laughing, whatever we do, group outings for meals will continue, so you Westeners should get used to it.",
                  ]}
                  isLeft={true}
                  isPrint={false}
                  setOnlineArticle={setOnlineArticle}
                />
              </div>
            </div>
            <Footer />
          </div>
        </Route>
      </Switch>
    </Router>
  );
};

export default PublicationsEng;
